### ISSUE TITLE
Notification Component UI

### ISSUE THREAD

**Issue by codebyviral** [codebyviral/iisppr-intern-management#3]
Create a responsive Notification Component UI. 
<img width="912" alt="Screenshot 2024-12-13 at 9 29 46 PM" src="https://github.com/user-attachments/assets/456007ca-8b8d-48de-b061-e460c49707e7" />

**Comment by harshsahu383** [comment]
clos

**Comment by BlueStorm02** [comment]
Branch - shivam
Pull Request - https://github.com/codebyviral/iisppr-intern-management/pull/11
Message - UI Design for Filter Option
